# Site settings
title: Željka Rajak
email: semzeljka@gmail.com
description: Dnevna inspiracija
baseurl: "/zeljkarajak.github.io"
url: "http://zeljkarajak.github.io"

author:
  name     : 'Željka Rajak'
  email    : semzeljka@gmail.com
  url      : http://zeljkarajak.github.io
  facebook : http://facebook.com/zeljka.rajak
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/zeljkarajak
disqus_shortname: "zeljkarajak"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
